In [19]:
import pandas as pd
import numpy as np
import nltk

In [ ]:
def listToString(s): 
    
    # initialize an empty string
    str1 = "" 
    
    # traverse in the string  
    for ele in s: 
        str1 = str1+" "+ele  
    
    # return string  
    return str1 

In [13]:
df=pd.read_csv(r"C:\Users\Nikhi\OneDrive - purdue.edu\Mod 2\Analyzing Unstructured Data\Group Project\UpdatedResumeDataSet.csv\UpdatedResumeDataSet.csv")

In [14]:
df.shape

(962, 2)

In [ ]:
df.head()
df['Category'].value_counts()

In [17]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
df['target'] = labelencoder.fit_transform(df['Category'])

In [21]:
df['target'].value_counts().sort_index()
y=df[['target']]
X=df[['Resume']]

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.3,random_state=13)

In [30]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(673, 1)
(673, 1)
(289, 1)
(289, 1)


In [31]:
#Transforming the data into training data 
#Tokenize the collection 
token_list=[]
for i in X_train['Resume']:
    token_list.append(nltk.word_tokenize(i))
#print(len(token_list))
#Lammetize the words 
lammetize_list=[]
for i in token_list:
    lemmatizer=nltk.stem.WordNetLemmatizer()
    lemmatized_token=[lemmatizer.lemmatize(token) for token in i]
    lammetize_list.append(lemmatized_token)
#Remove stop words
from nltk.corpus import stopwords
stop_list=[]
for i in lammetize_list:
    stop_words_removed = [token for token in i if not token in stopwords.words('english') if token.isalpha()]
    stop_list.append(stop_words_removed)


In [33]:
final_list=[]
for i in stop_list:
    sentence_list=listToString(i)
    final_list.append(sentence_list)
#TFIDF min_df=3 and include 2-gram 
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(min_df=5)
v1=vectorizer.fit(final_list)
v2=vectorizer.transform(final_list)
print(len(v1.vocabulary_.keys()))
X_train=pd.DataFrame(v2.toarray(),columns=v1.vocabulary_.keys())
X_train.head()

4276


operating  system  ubuntu  windows  other  tool  tableau       svn  beyond  \
0        0.0     0.0     0.0      0.0    0.0   0.0      0.0  0.000000     0.0   
1        0.0     0.0     0.0      0.0    0.0   0.0      0.0  0.000000     0.0   
2        0.0     0.0     0.0      0.0    0.0   0.0      0.0  0.025934     0.0   
3        0.0     0.0     0.0      0.0    0.0   0.0      0.0  0.000000     0.0   
4        0.0     0.0     0.0      0.0    0.0   0.0      0.0  0.000000     0.0   

   details  ...  formerly  preprocessing  prompt  labour  investigation  \
0      0.0  ...       0.0            0.0     0.0     0.0            0.0   
1      0.0  ...       0.0            0.0     0.0     0.0            0.0   
2      0.0  ...       0.0            0.0     0.0     0.0            0.0   
3      0.0  ...       0.0            0.0     0.0     0.0            0.0   
4      0.0  ...       0.0            0.0     0.0     0.0            0.0   

   scale  requested  temporary  wise  mainly  
0    0.0        0.0        0.0   0.0     0.0  
1    0.0        0.0        0.0   0.0     0.0  
2    0.0        0.0        0.0   0.0     0.0  
3    0.0        0.0        0.0   0.0     0.0  
4    0.0        0.0        0.0   0.0     0.0  

[5 rows x 4276 columns]

## Preprocessing Done 

### Preparing the test data 

In [35]:
#Transforming the data into training data 
#Tokenize the collection 
token_list_test=[]
for i in X_test['Resume']:
    token_list_test.append(nltk.word_tokenize(i))
#print(len(token_list))
#Lammetize the words 
lammetize_list_test=[]
for i in token_list_test:
    lemmatizer=nltk.stem.WordNetLemmatizer()
    lemmatized_token=[lemmatizer.lemmatize(token) for token in i]
    lammetize_list_test.append(lemmatized_token)
#Remove stop words
from nltk.corpus import stopwords
stop_list_test=[]
for i in lammetize_list_test:
    stop_words_removed = [token for token in i if not token in stopwords.words('english') if token.isalpha()]
    stop_list_test.append(stop_words_removed)


In [36]:
final_list_test=[]
for i in stop_list_test:
    sentence_list=listToString(i)
    final_list_test.append(sentence_list)
#Changing it w.r.t Tfidf vector 
v_test=vectorizer.transform(final_list_test)
X_test=pd.DataFrame(v_test.toarray(),columns=v1.vocabulary_.keys())
X_test.head()

operating  system  ubuntu  windows  other  tool  tableau  svn  beyond  \
0        0.0     0.0     0.0      0.0    0.0   0.0      0.0  0.0     0.0   
1        0.0     0.0     0.0      0.0    0.0   0.0      0.0  0.0     0.0   
2        0.0     0.0     0.0      0.0    0.0   0.0      0.0  0.0     0.0   
3        0.0     0.0     0.0      0.0    0.0   0.0      0.0  0.0     0.0   
4        0.0     0.0     0.0      0.0    0.0   0.0      0.0  0.0     0.0   

   details  ...  formerly  preprocessing  prompt  labour  investigation  \
0      0.0  ...       0.0            0.0     0.0     0.0            0.0   
1      0.0  ...       0.0            0.0     0.0     0.0            0.0   
2      0.0  ...       0.0            0.0     0.0     0.0            0.0   
3      0.0  ...       0.0            0.0     0.0     0.0            0.0   
4      0.0  ...       0.0            0.0     0.0     0.0            0.0   

   scale  requested  temporary  wise  mainly  
0    0.0        0.0   0.066912   0.0     0.0  
1    0.0        0.0   0.000000   0.0     0.0  
2    0.0        0.0   0.000000   0.0     0.0  
3    0.0        0.0   0.000000   0.0     0.0  
4    0.0        0.0   0.000000   0.0     0.0  

[5 rows x 4276 columns]

### Model Development 

### Naive Bayes

In [72]:
from sklearn.metrics import accuracy_score
## Naive Bayes
from sklearn.naive_bayes import MultinomialNB
NBmodel = MultinomialNB()
# training
NBmodel.fit(X_train, Y_train)
y_pred_NB = NBmodel.predict(X_test)
# evaluation
acc_NB = accuracy_score(Y_test, y_pred_NB)
print("Naive Bayes model Accuracy:: {:.4f}%".format(acc_NB*100))
y_pred_prob_nb = NBmodel.predict_proba(X_test)
print(y_pred_prob_nb[0])

Naive Bayes model Accuracy:: 91.6955%
[0.00319434 0.00504505 0.00636596 0.79063666 0.00699991 0.00411881
 0.01122761 0.00613479 0.01526078 0.00679081 0.00828858 0.00415108
 0.00977556 0.00856221 0.00353724 0.03502325 0.00651351 0.00526119
 0.00555432 0.00508201 0.01012819 0.00439054 0.00725091 0.01698834
 0.01371836]


C:\Users\Nikhi\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


### Logistic Regression

In [74]:
from sklearn.linear_model import LogisticRegression
Logitmodel = LogisticRegression()
# training
Logitmodel.fit(X_train, Y_train)
y_pred_logit = Logitmodel.predict(X_test)
# evaluation
from sklearn.metrics import accuracy_score
acc_logit = accuracy_score(Y_test, y_pred_logit)
print("Logit model Accuracy:: {:.4f}%".format(acc_logit*100))
y_pred_prob_logit = Logitmodel.predict_proba(X_test)
print(y_pred_prob_logit[0])

C:\Users\Nikhi\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Logit model Accuracy:: 98.9619%
[0.01381395 0.01717804 0.01570527 0.59715075 0.01718739 0.01184264
 0.01884176 0.01509224 0.01927823 0.0167682  0.01485967 0.01305056
 0.02234466 0.01397058 0.01241156 0.02650485 0.01726322 0.01363095
 0.01519109 0.01179239 0.01721641 0.01297328 0.01741791 0.02597929
 0.0225351 ]


### Decision Tree

In [73]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.metrics import accuracy_score
DTmodel = DecisionTreeClassifier(min_samples_leaf=15,random_state=0) ## number of trees and number of layers/depth
#training
DTmodel.fit(X_train, Y_train)
y_pred_DT = DTmodel.predict(X_test)
#evaluation
acc_DT = accuracy_score(Y_test, y_pred_DT)
print("Decision Tree Model Accuracy: {:.4f}%".format(acc_DT*100))
y_pred_prob_dt = DTmodel.predict_proba(X_test)
print(y_pred_prob_dt[0])

Decision Tree Model Accuracy: 90.3114%
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


### Random Forest Classifier 

In [71]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
RFmodel = RandomForestClassifier(n_estimators=100, max_depth=15, bootstrap=True, random_state=0) ## number of trees and number of layers/depth
#training
RFmodel.fit(X_train, Y_train)
y_pred_RF = RFmodel.predict(X_test)
#evaluation
acc_RF = accuracy_score(Y_test, y_pred_RF)
print("Random Forest Model Accuracy: {:.4f}%".format(acc_RF*100))
y_pred_prob_rf = RFmodel.predict_proba(X_test)
print(y_pred_prob_rf)

<ipython-input-71-4ce8e5bd9cf5>:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RFmodel.fit(X_train, Y_train)


Random Forest Model Accuracy: 98.9619%
[[0.01257841 0.02184149 0.00923925 ... 0.00881198 0.02434495 0.01041033]
 [0.01733796 0.02681144 0.01432071 ... 0.01821479 0.03856568 0.02071755]
 [0.02148637 0.03617315 0.01435552 ... 0.02095914 0.57284034 0.01818436]
 ...
 [0.02023155 0.034377   0.01476275 ... 0.0216357  0.05293243 0.0218633 ]
 [0.02678623 0.0455098  0.01629178 ... 0.02891813 0.04583765 0.03650271]
 [0.00635249 0.01251627 0.00568129 ... 0.01020861 0.01562373 0.00747624]]


### Xgboost Classifier 

In [43]:
from xgboost import XGBClassifier
xgmodel = XGBClassifier(random_state=0) ## number of trees and number of layers/depth
#training
xgmodel.fit(X_train, Y_train)
y_pred_xg = xgmodel.predict(X_test)
#evaluation
acc_xg = accuracy_score(Y_test, y_pred_xg)
print("Xgboost Classifier Model Accuracy: {:.4f}%".format(acc_xg*100))
y_pred_prob_xg = xgmodel.predict_proba(X_test)
print(y_pred_prob_xg[0])

C:\Users\Nikhi\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Nikhi\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


[20:37:51] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Random Forest Model Accuracy: 99.3080%
[[5.3137308e-04 4.4558811e-04 6.8680302e-04 ... 4.6680961e-04
  1.1671365e-03 6.0045754e-04]
 [8.4786845e-04 1.4594939e-03 9.9065143e-04 ... 7.4070628e-04
  7.3935761e-04 4.8146606e-03]
 [9.8041455e-05 3.9738195e-04 1.0416552e-04 ... 8.4701314e-05
  9.9161303e-01 8.4463434e-05]
 ...
 [5.1715469e-04 1.0332038e-03 5.4945797e-04 ... 4.9518252e-04
  2.8547538e-03 5.7256583e-04]
 [1.3150903e-03 1.0785164e-03 9.8097685e-04 ... 7.2777580e-04
  4.3217928e-04 8.7529246e-04]
 [2.5767225e-04 2.2758610e-04 5.2053439e-03 ... 2.0310495e-04
  9.8036358e-04 2.8061567e-04]]


### Light GBM Classifier 

In [47]:
import lightgbm as lgb
lgbmodel = lgb.LGBMClassifier(learning_rate=0.09,max_depth=-5,random_state=0) ## number of trees and number of layers/depth
#training
lgbmodel.fit(X_train, Y_train, verbose=20,eval_metric='logloss')
y_pred_lgb = lgbmodel.predict(X_test)
#evaluation
acc_lgb = accuracy_score(Y_test, y_pred_lgb)
print("Light GMB Classifier Model Accuracy: {:.4f}%".format(acc_lgb*100))
y_pred_prob_lgb = lgbmodel.predict_proba(X_test)
print(y_pred_prob_lgb[0])

C:\Users\Nikhi\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Nikhi\anaconda3\lib\site-packages\lightgbm\sklearn.py:736: UserWarning: 'verbose' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose' argument is deprecated and will be removed in a future release of LightGBM. "


Light GMB Classifier Model Accuracy: 99.6540%
[2.47310472e-07 1.03691051e-06 3.90863311e-07 9.99984195e-01
 5.05927342e-07 5.79996676e-07 3.52000609e-07 7.59502136e-07
 6.53876582e-07 5.75071039e-07 9.56565532e-07 4.22409233e-07
 8.22910914e-07 8.50592353e-07 8.50103112e-07 9.06481693e-07
 8.19447031e-07 5.59629307e-07 5.94332802e-07 5.84609478e-07
 6.10846725e-07 4.89885364e-07 3.46920910e-07 1.08524043e-06
 8.03485990e-07]


### CAT Boost Classifier 

In [58]:
from catboost import CatBoostClassifier
catmodel = CatBoostClassifier(random_state=0) ## number of trees and number of layers/depth
#training
catmodel.fit(X_train, Y_train, verbose=20)
y_pred_cat = catmodel.predict(X_test)
#evaluation
acc_cat = accuracy_score(Y_test, y_pred_cat)
print("Light GMB Classifier Model Accuracy: {:.4f}%".format(acc_cat*100))
y_pred_prob_cat = catmodel.predict_proba(X_test)
print(y_pred_prob_cat[0])

Learning rate set to 0.077545
0:	learn: 3.0990674	total: 320ms	remaining: 5m 19s
20:	learn: 1.9548077	total: 4.35s	remaining: 3m 22s
40:	learn: 1.2744040	total: 8.35s	remaining: 3m 15s
60:	learn: 0.8894125	total: 12.6s	remaining: 3m 13s
80:	learn: 0.6315302	total: 17.3s	remaining: 3m 15s
100:	learn: 0.4498025	total: 22.1s	remaining: 3m 17s
120:	learn: 0.3225946	total: 26.7s	remaining: 3m 14s
140:	learn: 0.2464941	total: 31.4s	remaining: 3m 11s
160:	learn: 0.1951020	total: 35.9s	remaining: 3m 7s
180:	learn: 0.1546790	total: 40.5s	remaining: 3m 3s
200:	learn: 0.1277455	total: 45.6s	remaining: 3m 1s
220:	learn: 0.1087157	total: 50.8s	remaining: 2m 58s
240:	learn: 0.0912137	total: 55.9s	remaining: 2m 55s
260:	learn: 0.0806826	total: 1m	remaining: 2m 51s
280:	learn: 0.0705201	total: 1m 5s	remaining: 2m 48s
300:	learn: 0.0627255	total: 1m 10s	remaining: 2m 44s
320:	learn: 0.0550937	total: 1m 15s	remaining: 2m 40s
340:	learn: 0.0492076	total: 1m 22s	remaining: 2m 39s
360:	learn: 0.0445799	tot

### ANN

In [63]:
## Neural Network and Deep Learning
from sklearn.neural_network import MLPClassifier
DLmodel = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(20,6), random_state=1)
# training
DLmodel.fit(X_train, Y_train)
y_pred_DL= DLmodel.predict(X_test)
# evaluation
acc_DL = accuracy_score(Y_test, y_pred_DL)
print("DL model Accuracy: {:.4f}%".format(acc_DL*100))
y_pred_prob_dl = DLmodel.predict_proba(X_test)
print(y_pred_prob_dl[0])

C:\Users\Nikhi\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


DL model Accuracy: 98.9619%
[0.00000000e+000 4.55114054e-226 7.42228163e-197 9.99999992e-001
 9.64957015e-284 2.27765274e-294 8.10643428e-172 2.42602206e-195
 0.00000000e+000 0.00000000e+000 3.78941871e-219 3.76466386e-264
 0.00000000e+000 8.19904303e-009 0.00000000e+000 0.00000000e+000
 1.66151441e-106 1.52499044e-252 6.73010271e-197 2.17080459e-086
 0.00000000e+000 2.67131413e-319 5.26175983e-115 0.00000000e+000
 2.35295953e-114]


### LSTM 

In [92]:
#Splitting the data as this needs different inputs 
y_lstm=df[['target']]
X_lstm=df[['Resume']]
from sklearn.model_selection import train_test_split
X_train_lstm,X_test_lstm,Y_train_lstm,Y_test_lstm=train_test_split(X_lstm,y_lstm,test_size=0.3,random_state=13)

In [93]:
#encoding each label and transforming both train and test datasets 
from numpy import array
from sklearn.preprocessing import LabelEncoder
tokenized_list= [nltk.word_tokenize(doc.lower()) for doc in df['Resume']]
tokenized_list_test= [nltk.word_tokenize(doc.lower()) for doc in X_test_lstm['Resume']]
tokenized_list_train= [nltk.word_tokenize(doc.lower()) for doc in X_train_lstm['Resume']]
# A set for all possible words
words = [j for i in tokenized_list for j in i]
total_words=len(words)
index_encoder = LabelEncoder()
index_encoder = index_encoder.fit(words) # define vocabulary
X_train_lstm = [index_encoder.transform(doc) for doc in tokenized_list_train]
X_test_lstm = [index_encoder.transform(doc) for doc in tokenized_list_test]

In [ ]:
# build model
from keras.preprocessing import sequence 
from keras.models import Sequential 
from keras.layers import Dense, Embedding, Flatten
from keras.layers import LSTM
max_features = total_words
maxlen = 2000
batch_size = 50
# padding
x_train_lstm = sequence.pad_sequences(X_train_lstm, maxlen=maxlen)
x_test_lstm = sequence.pad_sequences(X_test_lstm, maxlen=maxlen)
# model architecture
model = Sequential()
model.add(Embedding(max_features, 40, input_length=maxlen))
model.add(LSTM(1000, dropout=0.20, recurrent_dropout=0.20))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train_lstm, Y_train_lstm, batch_size=batch_size, epochs=25, validation_data=(x_test_lstm, Y_test_lstm))